package manners

import (
	"log"
	"io/ioutil"
)

var logger = log.New(ioutil.Discard, "", 0)

// SetLogger changes the logger used for the startup and shutdown messages
// generated by Manners. By default, no log messages are emitted.
// To make Manners logging behave the same as per the standard
// log package, i.e. to stderr, use
// `SetLogger(log.New(os.Stderr, "", log.LstdFlags))`
func SetLogger(l *log.Logger) {
	logger = l
}

